//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusStatations.Mvc.UpdateMonitorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UpdateMonitorService.IUpdateMonitor")]
    public interface IUpdateMonitor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateMonitor/Update", ReplyAction="http://tempuri.org/IUpdateMonitor/UpdateResponse")]
        string Update(int stationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateMonitor/Update", ReplyAction="http://tempuri.org/IUpdateMonitor/UpdateResponse")]
        System.Threading.Tasks.Task<string> UpdateAsync(int stationId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateMonitorChannel : BusStatations.Mvc.UpdateMonitorService.IUpdateMonitor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateMonitorClient : System.ServiceModel.ClientBase<BusStatations.Mvc.UpdateMonitorService.IUpdateMonitor>, BusStatations.Mvc.UpdateMonitorService.IUpdateMonitor {
        
        public UpdateMonitorClient() {
        }
        
        public UpdateMonitorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateMonitorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateMonitorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateMonitorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Update(int stationId) {
            return base.Channel.Update(stationId);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAsync(int stationId) {
            return base.Channel.UpdateAsync(stationId);
        }
    }
}
